const questions = [
  {
    id: 1,
    question: "Which of the following is NOT part of what plants use to make food?",
    options: ["Water", "Carbon dioxide", "Moonlight", "Sunlight"],
    answer: "Moonlight",
    category: "Science",
    difficulty: "Easy",
  },
  {
    id: 2,
    question: "Which of the following is a use of carbon dioxide?",
    options: [
      "Used in fire extinguishers",
      "Used in electricity",
      "Used in water purification",
      "Used in fuel combustion",
    ],
    answer: "Used in fire extinguishers",
    category: "Science",
    difficulty: "Easy",
  },
  {
    id: 3,
    question: "What gas do human beings breathe out?",
    options: ["Hydrogen", "Carbon dioxide", "Oxygen", "Nitrogen"],
    answer: "Carbon dioxide",
    category: "Science",
    difficulty: "Easy",
  },
  {
    id: 4,
    question: "What gas do human beings breathe in?",
    options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Helium"],
    answer: "Oxygen",
    category: "Science",
    difficulty: "Easy",
  },
  {
    id: 5,
    question: "Carbon dioxide can get into the environment through?",
    options: [
      "Eating food",
      "Drinking water",
      "Breathing by humans and animals",
      "Photosynthesis",
    ],
    answer: "Breathing by humans and animals",
    category: "Science",
    difficulty: "Easy",
  },
  {
    id: 6,
    question: "What is the powerhouse of the cell?",
    options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi Apparatus"],
    answer: "Mitochondria",
    category: "Biology",
    difficulty: "Medium",
  },
  {
    id: 7,
    question: "What is the largest planet in our Solar System?",
    options: ["Saturn", "Neptune", "Jupiter", "Uranus"],
    answer: "Jupiter",
    category: "Astronomy",
    difficulty: "Medium",
  },
  {
    id: 8,
    question: "How many bones are in the adult human body?",
    options: ["196", "206", "216", "226"],
    answer: "206",
    category: "Biology",
    difficulty: "Medium",
  },
  {
    id: 9,
    question: "What is the chemical symbol for gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    answer: "Au",
    category: "Chemistry",
    difficulty: "Medium",
  },
  {
    id: 10,
    question: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Mercury"],
    answer: "Mars",
    category: "Astronomy",
    difficulty: "Easy",
  },
];

export default questions;
